pref('extensions.secureLogin@blueimp.net.name', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.description', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.homepageURL', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.shortcut', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.hideStatusbarIcon',true);
pref('extensions.secureLogin@blueimp.net.hideToolsMenu',false);
pref('extensions.secureLogin@blueimp.net.hideContextMenuItem',true);
pref('extensions.secureLogin@blueimp.net.hideToolbarButton',false);
pref('extensions.secureLogin@blueimp.net.hideToolbarButtonMenu',true);
pref('extensions.secureLogin@blueimp.net.searchLoginsOnload',false);
pref('extensions.secureLogin@blueimp.net.skipDuplicateActionForms',true);
pref('extensions.secureLogin@blueimp.net.highlightColor','#FF9900');
pref('extensions.secureLogin@blueimp.net.highlightOutlineStyle','solid');
pref('extensions.secureLogin@blueimp.net.highlightOutlineWidth',1);
pref('extensions.secureLogin@blueimp.net.highlightOutlineRadius',5);
pref('extensions.secureLogin@blueimp.net.highlightStyle','');
pref('extensions.secureLogin@blueimp.net.autoSubmitForm',true);
pref('extensions.secureLogin@blueimp.net.javascriptProtection',false);
pref('extensions.secureLogin@blueimp.net.playLoginFoundSound',false);
pref('extensions.secureLogin@blueimp.net.playLoginSound',false);
pref('extensions.secureLogin@blueimp.net.exceptionList','');
pref('extensions.secureLogin@blueimp.net.autofillFormsOnLogin',false);
pref('extensions.secureLogin@blueimp.net.secureLoginBookmarks',false);
pref('extensions.secureLogin@blueimp.net.secureLoginBookmarkHash','#secureLoginBookmark');
pref('extensions.secureLogin@blueimp.net.autoLogin',false);
pref('extensions.secureLogin@blueimp.net.autoLoginExceptions','');
pref('extensions.secureLogin@blueimp.net.defaultNotificationTimeout',3000);
pref('extensions.secureLogin@blueimp.net.defaultNotificationImage','chrome://secureLogin/skin/login-small.png');
pref('extensions.secureLogin@blueimp.net.helpURL', 'http://firefox.add0n.com/secure-login.html');
pref("extensions.secureLogin@blueimp.net.just_installed", true);
pref("extensions.secureLogin@blueimp.net.post_install_url", "http://firefox.add0n.com/secure-login.html");
pref("extensions.secureLogin@blueimp.net.doSorting", true);
pref("extensions.secureLogin@blueimp.net.searchVisibleFormsOnly", false);
pref("extensions.secureLogin@blueimp.net.maxNumberOfFormsToSearch", 20);
pref("extensions.secureLogin@blueimp.net.version", "");
pref("extensions.secureLogin@blueimp.net.welcome", true);
pref("extensions.secureLogin@blueimp.net.pcharset", "qwertyuioplkjhgfdsazxcvbnmQWERTYUIOPLKJHGFDSAZXCVBNM1234567890");
pref("extensions.secureLogin@blueimp.net.plength", 12);
